### ISSUE TITLE
Loading css using style-loader and css-loader does not work

### ISSUE THREAD

**Issue by amite** [mhaagens/hot-reload-all-the-things#2]
I added a file.css in the `commons` folder

and try to import it like so in `App.js`

`import css from './file.css';`

I add `style-loader` and `css-loader` to your setup (inside the rules block)

```
{
    test: /\.css$/,
    use: [ 'style-loader', 'css-loader' ]
}
```

When I run `npm start` I get Module parse failed:

<img width="554" alt="screenshot 2017-03-02 15 56 12" src="https://cloud.githubusercontent.com/assets/1308947/23503238/cdf1d306-ff60-11e6-8ae8-2b00d6656636.png">

What am I doing wrong?

Here is my full `webpack.config.client.js` file for reference:

```
const webpack = require("webpack");
const path = require("path");

module.exports = {
  devtool: "inline-source-map",
  entry: [
    "react-hot-loader/patch",
    "webpack-dev-server/client?http://localhost:3001",
    "webpack/hot/only-dev-server",
    "./client/index",
  ],
  target: "web",
  module: {
    rules: [
      {
        test: /\.js?$/,
        use: "babel-loader",
        include: [
          path.join(__dirname, "client"),
          path.join(__dirname, "common"),
        ],
      },
      {
        test: /\.css$/,
        use: [ 'style-loader', 'css-loader' ]
      }
    ],
  },
  plugins: [
    new webpack.NamedModulesPlugin(),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoEmitOnErrorsPlugin(),
    new webpack.DefinePlugin({
      "process.env": { BUILD_TARGET: JSON.stringify("client") },
    }),
  ],
  devServer: {
    host: "localhost",
    port: 3001,
    historyApiFallback: true,
    hot: true,
  },
  output: {
    path: path.join(__dirname, ".build"),
    publicPath: "http://localhost:3001/",
    filename: "client.js",
  },
};
```

`require('./file.css');` also doesn't work

**Comment by mhaagens** [comment]
You don't import style.css in App.js, you import it in /client/index.js, the server doesn't know how to handle CSS/images etc. Look into https://github.com/jchip/isomorphic-loader.
This is just a starting point for getting up and running with hot reloading, not a fully fledged boilerplate.

**Comment by amite** [comment]
Thanks @mhaagens - just trying to extend it into one - I really like the way you set it up and I can understand most of it now as opposed to those other solutions.

**Comment by mhaagens** [comment]
That's great! Let me know if you finish it, would love to check it out!

**Comment by amite** [comment]
FYI: I am trying to set it up like you did your other mobx boilerplate

**Comment by mhaagens** [comment]
That would be really cool!
