### ISSUE TITLE
Need help to make koa server hot-reloading

### ISSUE THREAD

**Issue by budarin** [mhaagens/hot-reload-all-the-things#4]
Create simple koa server with hot-reloading like in your article 
[simple-koa-hot-reloading-server](https://github.com/budarin/koa-hot-reload)

Page does not update after refresh while recompiling.
Thanks

**Comment by mhaagens** [comment]
Try this;
```
import http from 'http';
import app from './server';

const port = 3000;

const server = http.createServer(app.callback()).listen(3000);

if (module.hot) {
    module.hot.accept('./server', () => {
        server.removeAllListeners('request', server);
        server.on('request', app.callback())
    });
}

console.log(`Server running on: http://localhost: ${port}`);
```

**Comment by budarin** [comment]
Hi!

Thanks for reply, but unfortunately it doesnt work :(
Here is an error:

var server = 
__WEBPACK_IMPORTED_MODULE_0_http___default.a.createServer(__WEBPACK_IMPORTED_MODULE_1__server__["default"].callback()).listen(3000);
^

TypeError: __WEBPACK_IMPORTED_MODULE_1__server__.default.callback is not 
a function
     at Object../server/index.js (D:\Git 
Projects\hot-reload-all-the-things\.build\server.js:786:121)
     at __webpack_require__ (D:\Git 
Projects\hot-reload-all-the-things\.build\server.js:621:30)
     at fn (D:\Git 
Projects\hot-reload-all-the-things\.build\server.js:45:20)
     at Object.4 (D:\Git 
Projects\hot-reload-all-the-things\.build\server.js:867:18)
     at __webpack_require__ (D:\Git 
Projects\hot-reload-all-the-things\.build\server.js:621:30)
     at D:\Git Projects\hot-reload-all-the-things\.build\server.js:670:37
     at Object.<anonymous> (D:\Git 
Projects\hot-reload-all-the-things\.build\server.js:673:10)
     at Module._compile (module.js:571:32)
     at Object.Module._extensions..js (module.js:580:10)
     at Module.load (module.js:488:32)


08.03.2017 0:20, Martin пишет:

**Comment by mhaagens** [comment]
Made a PR to your repo, see if that works for you.
You might need a .babelrc in your folder with;
```
{
	"presets": [
		["env", {"modules": false}]
	]
}
```

**Comment by budarin** [comment]
added .babelrc nothing changed - server doesn't restart
the problem is in koa listener pointer - I've wrote the team about the issue

**Comment by budarin** [comment]
thanks, your changes works (removeAllListeners)

**Comment by sibelius** [comment]
@budarin is repo is doing 404, do you have another repo that shows how this works?
